version: '3'
services:
  app:
    build: .
    ports:
     - "5000:80"
    volumes:
     - .:/bench
    networks:
    - benchnet   
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: elastic
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true 
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elastic-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - benchnet

volumes:
  elastic-data:
    driver: local

networks:
  benchnet:
    driver: bridge
